// Code generated by hertz generator.

package publish_gorm

import (
	"context"
	"github.com/DodiNCer/tiktok/biz/dal/mysql"
	"github.com/DodiNCer/tiktok/biz/model"
	"github.com/DodiNCer/tiktok/biz/model/favorite_gorm"
	"github.com/DodiNCer/tiktok/biz/model/follower_gorm"
	"github.com/DodiNCer/tiktok/biz/model/publish_gorm"
	"github.com/DodiNCer/tiktok/biz/util"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// PublishList .
// @router /douyin/publish/list/ [GET]
func PublishList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req publish_gorm.PublishListRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	reqUserId := req.UserID
	token := req.Token

	if err != nil {
		c.JSON(consts.StatusOK, &favorite_gorm.FavoriteActionResponse{
			StatusCode: follower_gorm.Code_RTErr,
			StatusMsg:  err.Error(),
		})
	}

	key, err := util.CheckToken(token)

	userId := key.UserId
	if err != nil {
		c.JSON(consts.StatusOK, &favorite_gorm.FavoriteActionResponse{
			StatusCode: follower_gorm.Code_RTErr,
			StatusMsg:  err.Error(),
		})
	}
	//验证参数里的id和token的id一致
	if reqUserId != userId {
		c.JSON(consts.StatusOK, &favorite_gorm.FavoriteActionResponse{
			StatusCode: follower_gorm.Code_RTErr,
			StatusMsg:  err.Error(),
		})
	}

	var videoListRes []*favorite_gorm.Video

	var videoList []*model.Video
	var user model.User
	var followCount int64
	var followerCount int64
	var favoriteCount int64
	var commentCount int64
	var isbool int64
	//数据库操作
	err = func() error {
		if err = mysql.DB.Where("id = ?", userId).Find(&user).Error; err != nil {
			return err
		}
		//查找视频作者关注总数
		if err = mysql.DB.Model(&model.Follower{}).Where("user_uid = ? And is_deleted = ?", user.Id, 0).
			Count(&followCount).Error; err != nil {
			return err
		}
		//查找视频作者粉丝总数
		if err = mysql.DB.Model(&model.Follower{}).Where("to_user_uid = ? And is_deleted = ?", userId, 0).
			Count(&followerCount).Error; err != nil {
			return err
		}
		userRes := &follower_gorm.User{
			ID:            user.Id,
			Name:          user.Name,
			FollowCount:   followCount,
			FollowerCount: followerCount,
			IsFollow:      false,
		}

		if err = mysql.DB.Where("creator_id = ? AND is_deleted = ?", userId, 0).Find(&videoList).Error; err != nil {
			return err
		}
		for _, video := range videoList {
			if err = mysql.DB.Model(&model.Favorite{}).Where("video_id = ? AND is_deleted = ?", video.Id, 0).
				Count(&favoriteCount).Error; err != nil {
				return err
			}
			if err = mysql.DB.Model(&model.Comment{}).Where("video_id = ? AND is_deleted = ?", video.Id, 0).
				Count(&commentCount).Error; err != nil {
				return err
			}
			if err = mysql.DB.Model(&model.Favorite{}).Where("creator_id = ? AND video_id = ? AND is_deleted = ?", userId, video.Id, 0).
				Count(&isbool).Error; err != nil {
				return err
			}
			videoListRes = append(videoListRes, &favorite_gorm.Video{
				ID:            video.Id,
				Author:        userRes,
				PlayURL:       video.Path,
				CoverURL:      video.CoverPath,
				FavoriteCount: favoriteCount,
				CommentCount:  commentCount,
				IsFavorite: func() bool {
					if isbool == 1 {
						return true
					} else {
						return false
					}
				}(),
				Title: video.Title,
			})
		}
		return nil
	}()
	if err != nil {
		c.JSON(consts.StatusOK, &favorite_gorm.FavoriteActionResponse{
			StatusCode: follower_gorm.Code_DBErr,
			StatusMsg:  err.Error(),
		})
	}

	resp := new(publish_gorm.PublishListResponse)
	resp.VideoList = videoListRes
	c.JSON(consts.StatusOK, resp)
}
