// Code generated by Kitex v0.4.4. DO NOT EDIT.
package kitexffmpeg

import (
	kitex_ffmpeg "github.com/DodiNCer/tiktok/biz/mw/kitex_ffmpeg"
	server "github.com/cloudwego/kitex/server"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler kitex_ffmpeg.KitexFfmpeg, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
