version: '3'
services:
  mysql:
    image: 'mysql:5'
    volumes:
      - ./biz/dal/sql:docker-entrypoint-initdb.d
      - ./sqldb:/var/lib/mysql
    ports:
      - 13306:3306
    environment:
      - MYSQL_DATABASE=tikton
      - MYSQL_USER=tiktok
      - MYSQL_PASSWORD=tiktok
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: 'redis:6'
    ports:
      - 16379:6379