version: '3'

services:
  mysql:
    image: 'mysql:8'
    volumes:
      - ./biz/dal/sql:/docker-entrypoint-initdb.d
      - ./data/mysql:/var/lib/mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_DATABASE=tiktok
      - MYSQL_USER=tiktok
      - MYSQL_PASSWORD=tiktok
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  kitex-ffmpeg:
    image: 'doudincer/kitex-ffmpeg:v1.1'
    ports:
      - '19427:9427'
    environment:
      - KITEX_FFMPEG_WORKDIR="/tmp/kitex_ffmpeg"
  minio-oss:
    image: 'minio/minio:latest'
    ports:
      - '19000:9000'
      - '19001:9001'
    volumes:
      - ./data/minio:/data
    environment:
      - MINIO_ROOT_USER=tiktok
      - MINIO_ROOT_PASSWORD=tiktokpass
    command: server /data --console-address ":9001" -address ":9000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:19000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
