// Code generated by hertz generator.

package main

import (
	"github.com/DodiNCer/tiktok/biz/dal"
	"github.com/DodiNCer/tiktok/biz/mw"
	"github.com/DodiNCer/tiktok/biz/router"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	h := server.Default(server.WithHostPorts("0.0.0.0:8086"))
	dal.Init()
	mw.InitRedis()
	router.Register(h)
	h.Spin()
}
