// Code generated by hertz generator.

package main

import (
	"github.com/DodiNCer/tiktok/biz/dal/sql"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	err := sql.InitDb()
	if err != nil {
		panic(err)
	}

	h := server.Default()
	register(h)
	h.Spin()
}
