// Code generated by hertz generator.

package main

import (
	"github.com/DodiNCer/tiktok/biz/dal/sql"
	"github.com/cloudwego/hertz/pkg/app/server"
)

func main() {
	//初始化gorm
	err := sql.InitDb()
	if err != nil {
		return
	}
	h := server.Default()

	register(h)
	h.Spin()
}
