// Code generated by hertz generator.

package main

import (
	handler "github.com/DodiNCer/tiktok/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	// your code ...
	r.POST("/douyin/user/register", handler.RegisterPing)
}
