// Code generated by hertz generator.

package follower_gorm

import (
	"context"
	"github.com/DodiNCer/tiktok/biz/dal/mysql"
	"github.com/DodiNCer/tiktok/biz/model"
	follower_gorm "github.com/DodiNCer/tiktok/biz/model/follower_gorm"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"strconv"
	"time"
)

// CreateFollower .
// @router /douyin/relation/action/ [POST]
func CreateFollower(ctx context.Context, c *app.RequestContext) {
	var err error
	var req follower_gorm.CreateFollowerRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	toUserUid, err := strconv.ParseInt(req.ToUserID, 10, 64)
	if err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	if err = mysql.CreateFollower([]*model.Follower{
		{
			ToUserUid:  toUserUid,
			UserUid:    2,
			CreateTime: time.Now(),
			IsDeleted:  false,
			UpdateTime: time.Now(),
		},
	}); err != nil {
		c.JSON(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(follower_gorm.CreateFollowerResponse)
	resp.StatusMsg = "关注成功"

	c.JSON(consts.StatusOK, resp)
}
