// Code generated by hertz generator.

package Feed

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feedMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryfeedlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _feed_gormMw() []app.HandlerFunc {
	// your code...
	return nil
}
