// Code generated by hertz generator.

package CommentGorm

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _douyinMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _commentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _actionMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _createcommentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _querycommentlistMw() []app.HandlerFunc {
	// your code...
	return nil
}
