// Code generated by hertz generator.

package register

import (
	handler "github.com/DodiNCer/tiktok/biz/handler"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// customizeRegister registers customize routers.
func CustomizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)
	// your code ...
}
